version: "3.0"

services:
  redis:
    image: "redis:6.0"
    ports:
      - 6379:6379

  app:
    image: "ptt:latest"
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
