Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision :shell, path: "vagrant/bootstrap.sh"
  config.vm.synced_folder "symfony", "/usr/share/nginx/html/"
end
