kind: ReplicationController
apiVersion: v1
metadata:
  name: ksh-rc
spec:
  replicas: 1
  selector:
    app: ksh
  template:
    metadata:
      labels:
        app: ksh
    spec:
      containers:
      - name: klog-cnt
        image: cn007b/ubuntu
        command: [
          'sh',
          '-c',
          "while true; do curl -i -XPOST 'https://realtimelog.herokuapp.com:443/ping' -H 'Content-Type: application/json' -d '{\"code\":\"100\", \"status\": \"ok from rc\"}'; sleep 5; done",
        ]
