nginx:
    image: nginx:latest
    restart: always
    ports:
        - "80:80"
    volumes:
        - ./ed:/var/www/html/gh/ed
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php-fpm

php-fpm:
    build: ./docker/php-fpm
    volumes:
        - ./ed:/var/www/html/gh/ed
    links:
        - mongo

phalcon:
    build: ./docker/phalcon

composer:
    image: composer/composer
    working_dir: /gh/ed
    volumes:
        - ./ed/docker/examples/one/src:/gh/ed
    command: install

mongo:
    image: mongo:latest
