nginx:
    image: nginx:latest
    restart: always
    ports:
        - "80:80"
    volumes:
        - ./ed:/var/www/html/gh/ed
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php-fpm

php-fpm:
    build: ./docker/php-fpm
    volumes:
        - ./ed:/var/www/html/gh/ed
    links:
        # - mysql
        - es

# With purpose to check php-cli just run:
# docker-compose run php-cli php /gh/ed/docker/examples/one/src/es.php
php-cli:
    build: ./docker/php-cli
    volumes:
        - ./ed:/gh/ed
    links:
        # - mysql
        - es

# composer:
#     image: composer/composer
#     volumes:
#         - ./ed:/gh/ed
#     command: install

es:
    image: elasticsearch:latest
    restart: always
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - ./docker/elasticsearch/config.yml:/etc/elasticsearch/elasticsearch.yml

# docker-compose run mysql /bin/bash
# docker run -d --name mydb --expose 3306 \     alpine:latest nc -l 0.0.0.0:3306
mysql:
    image: mysql:latest
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=dbu
        - MYSQL_PASSWORD=dbp
    ports:
        - "3306:3306"
