nginx:
    image: nginx:latest
    restart: always
    ports:
        - "80:80"
    volumes:
        - ./ed:/var/www/html/gh/ed
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php-fpm

php-fpm:
    build: ./docker/php-fpm
    volumes:
        - ./ed:/var/www/html/gh/ed
    links:
        - mysql
        - mongo
        - es

# With purpose to check php-cli just run:
# docker-compose exec php-cli php /gh/ed/docker/examples/one/src/es.php
php-cli:
    build: ./docker/php-cli
    volumes:
        - ./ed:/gh/ed
    links:
        - mysql
        - mongo
        - es

phalcon:
    build: ./docker/phalcon

# cd ./ed/docker/examples/one/src && docker run --rm -ti -v $PWD:/app composer install
composer:
    image: composer/composer
    working_dir: /gh/ed
    volumes:
        - ./ed/docker/examples/one/src:/gh/ed
    command: install

es:
    image: elasticsearch:latest
    restart: always
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - ./docker/elasticsearch/config.yml:/etc/elasticsearch/elasticsearch.yml

# docker-compose exec mysql /bin/bash
# docker-compose exec mysql service mysql status
# docker-compose exec mysql sh -c 'mysql -uUSR -pPWD -DDB < /data/mysql.dump.sql'
mysql:
    image: mysql:latest
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=dbu
        - MYSQL_PASSWORD=dbp
    ports:
        - "3306:3306"

mongo:
    image: mongo:latest
