FROM ubuntu:latest

RUN apt-get update && apt-get upgrade

RUN apt-get install -y curl git siege

# nodejs v 8
# RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
# RUN apt-get install -y nodejs

# nvm
# RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
