# FROM ubuntu:latest
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    vim git curl telnet net-tools siege

# # nodejs v 8
# RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
# RUN apt-get install -y nodejs
# # nvm
# RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
