apiVersion: v1
kind: Pod
metadata:
  name: ksh-pod
  labels:
    app: ksh
spec:
  containers:
  - name: ksh-container
    image: cn007b/ubuntu
    ports:
    - containerPort: 8080
    command: [
      'sh',
      '-c',
      # 'echo "it works, id: `uuid`";',
      "curl -i -XPOST 'https://realtimelog.herokuapp.com:443/ping' -H 'Content-Type: application/json' -d '{\"code\":\"200\", \"status\": \"OK\"}'",
    ]
