network.host: "172.17.0.3"
network.bind_host: ["172.17.0.3"]
http.port: 9200
cluster.name: ec
node.name: es-data-1
node.master: false
node.data: true
discovery.type: zen
discovery.zen.ping.multicast.enabled: true
discovery.zen.ping.unicast.hosts: ["172.17.0.2", "172.17.0.3"]
