apiVersion: v1
kind: ServiceAccount
metadata:
  name: random-sa
  namespace: default
automountServiceAccountToken: false

---

apiVersion: v1
kind: Pod
metadata:
  name: random
spec:
  serviceAccountName: default
  containers:
  volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vzfp7
      readOnly: true
  # ...
  volumes:
    - name: kube-api-access-vzfp7
      projected:
      defaultMode: 420
      sources:
        - serviceAccountToken:
          expirationSeconds: 3600
          path: token
