/*
npm install express

express site

npm install

Project generated by unit "Site" is not in production mode, to fix it:
$ export NODE_ENV=production
*/

// Example how config project generated by unit "Site".
app.configure(function(){
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.static(__dirname + '/public'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(function(req, res, next){
    res.send('Sorry ' + req.url + ' does not exist');
    });
});

// One more time:
app.configure(function(){
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.static(__dirname + '/public'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(function(req, res, next){
        throw new Error(req.url + ' not found');
    });
    app.use(function(err, req, res, next) {
        console.log(err);
        res.send(err.message);
    });
});