#network.bind_host: ["172.31.21.4"] 
#network.host: 0.0.0.0
#network.host: 0.0.0.0:ipv4_
#http.bind_host:
#network.host: _eth0:ipv4_

network.bind_host: ["0.0.0.0"]
http.port: 9201

# This is a Pure Master node

cluster.name: prod-zii
node.data: true
node.master: true
node.name: node01

discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.timeout: 10s
discovery.zen.ping.multicast.enabled: false
# Important
# Important to avoid undesared shards rebalancing between nodes.
# discovery.zen.ping.unicast.hosts: ["172.31.11.226", "172.31.3.106"]

network.host: _eth0:ipv4_
bootstrap.mlockall: true

index.number_of_shards: 5
index.number_of_replicas: 1

action.disable_delete_all_indices: true
action.destructive_requires_name: true

cloud.aws.access_key: "sdfsd"
cloud.aws.secret_key: "Lropthlfk"
discovery.type: ec2
discovery.ec2.groups: sg-b39627d4
plugin.mandatory: cloud-aws
cloud.aws.region: eu-west-1

http.cors.enabled: true

http.enabled: false # for data node - no query directly

# scripts

script.engine.groovy.inline.search: on
script.engine.groovy.inline.update: on
script.engine.groovy.inline.search: true
script.engine.groovy.inline.update: true
script.groovy.sandbox.enabled: true

# Important for performance after cluster maintenance.

# Wait until at least 8 nodes are present
# and start recovery when either 3 minutes passed
# or all 9 nodes are present and active.
gateway.recover_after_nodes: 8
gateway.expected_nodes: 9
gateway.recover_after_nodes: 3m
