
#network.bind_host: ["172.31.21.4"] 
#network.host: 0.0.0.0 
#network.host: 0.0.0.0:ipv4_ 
#http.bind_host: 
#network.host: _eth0:ipv4_ 

network.bind_host: ["0.0.0.0"]
http.port: 9201

script.engine.groovy.inline.search: on
script.engine.groovy.inline.update: on
