# USAGE:
#
# docker-compose -f ed/sh/docker/examples.docker-compose/go.db.docker-compose.yml up xmysql
# docker-compose -f ed/sh/docker/examples.docker-compose/go.db.docker-compose.yml up mysqlapp
#
# docker exec -it xmysql mysql -P3306 -udbu -pdbp -Dtest
# docker exec -it xmysqlapp /bin/bash

version: '3'

networks:
  prvt:
    internal: true
  publ:
    internal: false

services:

  xmysql:
    container_name: xmysql
    hostname: xmysql
    image: mysql:5.7.27
    networks:
      - prvt
    ports:
      - "3306:3306"
    # volumes:
      # - "$PWD/.docker/.data/mysql:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=dbu"
      - "MYSQL_PASSWORD=dbp"
      - "MYSQL_DATABASE=test"

  mysqlapp:
    container_name: xmysqlapp
    hostname: xmysqlapp
    image: cn007b/go
    depends_on:
      - xmysql
    networks:
      - prvt
      - publ
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/ed/l/go/examples/db/src/mysql:/gh/ed/l/go/examples/db/src/mysql"
    environment:
      - "GOPATH=/gh/ed/l/go/examples/db/"
    working_dir: /gh/ed/l/go/examples/db/
    command: bash -c "
        go get github.com/go-sql-driver/mysql;
        go run src/mysql/simple.go
      "
