elasticsearch1:
  image: elasticsearch:5.4.0
  container_name: elasticsearch1
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  mem_limit: 1g
  # volumes:
    # - esdata1:/usr/share/elasticsearch/data
  ports:
    - 9200:9200

elasticsearch2:
  image: elasticsearch:5.4.0
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.zen.ping.unicast.hosts=elasticsearch1"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  mem_limit: 1g
  # volumes:
    # - esdata2:/usr/share/elasticsearch/data
