FROM php:7.1-cli

RUN apt-get update
    # && apt-get install -y \
    # libmcrypt-dev libicu-dev mysql-client \
    # && docker-php-ext-install opcache common phpdbg dev \
    # && docker-php-ext-install mcrypt mbstring bcmath \
    # && docker-php-ext-install mysql pdo pdo_mysql php-mongodb sqlite sqlite3 redis \
    # && docker-php-ext-install dom xml json \
    # && docker-php-ext-install zip curl gd imap \

CMD ["php"]
