guest:
    resource: "@AppBundle/Controller/Guest"
    type:     annotation

account:
    resource: "@AppBundle/Controller/Account"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
