# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # AVAILABLE KERNEL EVENTS:
    #
    # kernel.request
    # kernel.view
    # kernel.finish_request
    # kernel.terminate
    # kernel.exception
    #
    # or run: php bin/console debug:event-dispatcher
    app.controller_listener:
        class: AppBundle\EventListener\MySymfonyListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    app.response_listener:
        class: AppBundle\EventListener\MySymfonyListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    app.console_command_listener:
        class: AppBundle\EventListener\MySymfonyListener
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
