# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # AVAILABLE KERNEL EVENTS:
    #
    # kernel.request
    # kernel.view
    # kernel.finish_request
    # kernel.terminate
    # kernel.exception
    #
    # or run: php bin/console debug:event-dispatcher
    app.controller_listener:
        class: AppBundle\EventListener\MySymfonyListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    app.response_listener:
        class: AppBundle\EventListener\MySymfonyListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    app.console_command_listener:
        class: AppBundle\EventListener\MySymfonyListener
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
    # app.doctrine_post_persist_listener:
    #     class: AppBundle\EventListener\MyDoctrineListener
    #     tags:
    #         - { name: doctrine.event_listener, event: postPersist, method: onPostPersist }
    # app.doctrine_subscriber_listener:
    #     class: AppBundle\EventListener\MyDoctrineListener
    #     tags:
    #         - { name: doctrine.event_subscriber, connection: default, method: onCustom }

    # Twig
    date.twig_extension:
        class: AppBundle\Twig\DateExtension
        public: false
        tags:
            - { name: twig.extension }
    comments.twig_function:
        class: AppBundle\Twig\CommentsExtension
        arguments: ['@service_container']
        public: false
        tags:
            - { name: twig.extension }

    # DOMAIN MODEL
    comment:
        class: AppBundle\DomainModel\Comment
        arguments:
            - '@doctrine.orm.slave_entity_manager'
            - '@doctrine.orm.master_entity_manager'
