# workflow

name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: .

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build 1.17-alpine
      run: docker build . -f ./docker/1.17-alpine/Dockerfile -t cn007b/go:1.17-alpine-$(date +%s)
