name: "Migrate spanner"
description: "Migrate spanner action"

inputs:
  workload-identity-provider:
    required: true
    description: "Workload identity provider"
  service-account-email:
    required: true
    description: "Service account email"
  env-name:
    description: "Environment name"
    required: true
  project-id:
    description: "GCP project ID"
    required: true
  spanner-instance-name:
    description: "Spanner instance name"
    required: true
  spanner-db-name:
    description: "Spanner DB name"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout source code"
      uses: actions/checkout@v3
    - name: "Authenticate to Google Cloud"
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
        service_account: ${{ inputs.service-account-email }}
    - name: "Migrate"
      shell: bash
      env:
        PRJ: ${{ inputs.project-id }}
        DBI: ${{ inputs.spanner-instance-name }}
        DB: ${{ inputs.spanner-db-name }}
      run: |
        make migrate-init
        make load-migrations
