# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    monolog.logger.my_cli:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@monolog.logger.my_cli_handler]]
    monolog.logger.my_cli_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%.my_cli.log, 200] # 200 - info
    # app.exception_listener:
    #     class: AppBundle\EventListener\ExceptionListener
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.exception }
    app.exception_subscriber:
        class: AppBundle\EventSubscriber\ExceptionSubscriber
        tags:
            - { name: kernel.event_subscriber }
    custom.event.home_page_event:
        class: AppBundle\EventSubscriber\HomePageEventSubscriber
        tags:
            - { name: kernel.event_listener, event: custom.event.home_page_event, method: onCustomEvent }
