# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    monolog.logger.my_cli:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@monolog.logger.my_cli_handler]]
    monolog.logger.my_cli_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%.my_cli.log, 200] # 200 - info
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
