app_model_api:
    resource: "@AppBundle/Controller/ModelRESTController.php"
    type:   rest
    prefix:   /api

app_vendor_api:
    resource: "@AppBundle/Controller/VendorRESTController.php"
    type:   rest
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
acme_website:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix: /
lang:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /{_locale}/lang

