// Code generated by protoc-gen-go. DO NOT EDIT.
// source: one.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Port struct {
	ID                   string    `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	City                 string    `protobuf:"bytes,3,opt,name=City,proto3" json:"City,omitempty"`
	Country              string    `protobuf:"bytes,4,opt,name=Country,proto3" json:"Country,omitempty"`
	Alias                []string  `protobuf:"bytes,5,rep,name=Alias,proto3" json:"Alias,omitempty"`
	Regions              []string  `protobuf:"bytes,6,rep,name=Regions,proto3" json:"Regions,omitempty"`
	Coordinates          []float32 `protobuf:"fixed32,7,rep,packed,name=Coordinates,proto3" json:"Coordinates,omitempty"`
	Province             string    `protobuf:"bytes,8,opt,name=Province,proto3" json:"Province,omitempty"`
	Timezone             string    `protobuf:"bytes,9,opt,name=Timezone,proto3" json:"Timezone,omitempty"`
	Unlocs               []string  `protobuf:"bytes,10,rep,name=Unlocs,proto3" json:"Unlocs,omitempty"`
	Code                 string    `protobuf:"bytes,11,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Port) Reset()         { *m = Port{} }
func (m *Port) String() string { return proto.CompactTextString(m) }
func (*Port) ProtoMessage()    {}
func (*Port) Descriptor() ([]byte, []int) {
	return fileDescriptor_322e57bd7c757107, []int{0}
}

func (m *Port) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Port.Unmarshal(m, b)
}
func (m *Port) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Port.Marshal(b, m, deterministic)
}
func (m *Port) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Port.Merge(m, src)
}
func (m *Port) XXX_Size() int {
	return xxx_messageInfo_Port.Size(m)
}
func (m *Port) XXX_DiscardUnknown() {
	xxx_messageInfo_Port.DiscardUnknown(m)
}

var xxx_messageInfo_Port proto.InternalMessageInfo

func (m *Port) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Port) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Port) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Port) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Port) GetAlias() []string {
	if m != nil {
		return m.Alias
	}
	return nil
}

func (m *Port) GetRegions() []string {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *Port) GetCoordinates() []float32 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Port) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Port) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *Port) GetUnlocs() []string {
	if m != nil {
		return m.Unlocs
	}
	return nil
}

func (m *Port) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type GetRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_322e57bd7c757107, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *Port    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_322e57bd7c757107, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetResponse) GetData() *Port {
	if m != nil {
		return m.Data
	}
	return nil
}

type PutResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_322e57bd7c757107, []int{3}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *PutResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Port)(nil), "proto.Port")
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "proto.GetResponse")
	proto.RegisterType((*PutResponse)(nil), "proto.PutResponse")
}

func init() { proto.RegisterFile("one.proto", fileDescriptor_322e57bd7c757107) }

var fileDescriptor_322e57bd7c757107 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdb, 0x24, 0xfd, 0x93, 0x09, 0xbc, 0xf0, 0x0e, 0x22, 0x4b, 0x11, 0x0c, 0x39, 0xe5,
	0xd4, 0x43, 0x3d, 0x78, 0x96, 0x16, 0x4a, 0x2f, 0x12, 0xa2, 0x7e, 0x80, 0xd8, 0x0c, 0x25, 0xd0,
	0xee, 0xd4, 0xdd, 0x4d, 0xa1, 0x7e, 0x08, 0x3f, 0xb3, 0xec, 0x6e, 0x5a, 0x03, 0x1e, 0x3c, 0x65,
	0x9f, 0xdf, 0x4c, 0xe6, 0x99, 0x79, 0x20, 0x66, 0x49, 0xf3, 0xa3, 0x62, 0xc3, 0x38, 0x72, 0x9f,
	0xec, 0x2b, 0x80, 0xa8, 0x60, 0x65, 0xf0, 0x1f, 0x04, 0x9b, 0x95, 0x18, 0xa6, 0xc3, 0x3c, 0x2e,
	0x83, 0xcd, 0x0a, 0x11, 0xa2, 0xe7, 0xea, 0x40, 0x22, 0x70, 0xc4, 0xbd, 0x2d, 0x5b, 0x36, 0xe6,
	0x2c, 0x42, 0xcf, 0xec, 0x1b, 0x05, 0x4c, 0x96, 0xdc, 0x4a, 0xa3, 0xce, 0x22, 0x72, 0xf8, 0x22,
	0xf1, 0x06, 0x46, 0x4f, 0xfb, 0xa6, 0xd2, 0x62, 0x94, 0x86, 0x79, 0x5c, 0x7a, 0x61, 0xfb, 0x4b,
	0xda, 0x35, 0x2c, 0xb5, 0x18, 0x3b, 0x7e, 0x91, 0x98, 0x42, 0xb2, 0x64, 0x56, 0x75, 0x23, 0x2b,
	0x43, 0x5a, 0x4c, 0xd2, 0x30, 0x0f, 0xca, 0x3e, 0xc2, 0x19, 0x4c, 0x0b, 0xc5, 0xa7, 0x46, 0x6e,
	0x49, 0x4c, 0x9d, 0xd9, 0x55, 0xdb, 0xda, 0x6b, 0x73, 0xa0, 0x4f, 0x96, 0x24, 0x62, 0x5f, 0xbb,
	0x68, 0xbc, 0x85, 0xf1, 0x9b, 0xdc, 0xf3, 0x56, 0x0b, 0x70, 0x96, 0x9d, 0x72, 0xf7, 0x70, 0x4d,
	0x22, 0xe9, 0xee, 0xe1, 0x9a, 0xb2, 0x3b, 0x80, 0x35, 0x99, 0x92, 0x3e, 0x5a, 0xd2, 0xbf, 0x52,
	0xc9, 0x56, 0x90, 0xb8, 0xaa, 0x3e, 0xb2, 0xd4, 0x64, 0x4f, 0x24, 0xa5, 0x58, 0x75, 0x1d, 0x5e,
	0xe0, 0x3d, 0x44, 0x75, 0x65, 0x2a, 0x17, 0x5d, 0xb2, 0x48, 0x7c, 0xe0, 0x73, 0x9b, 0x72, 0xe9,
	0x0a, 0xd9, 0x23, 0x24, 0x45, 0xfb, 0xd7, 0x14, 0xec, 0x4d, 0x89, 0xfd, 0x8f, 0x8b, 0x1d, 0x24,
	0x76, 0xcc, 0x0b, 0xa9, 0x53, 0xb3, 0x25, 0x9c, 0x43, 0xb8, 0x26, 0x83, 0xff, 0x3b, 0x87, 0x9f,
	0xbd, 0x67, 0xd8, 0x47, 0xde, 0x26, 0x1b, 0x60, 0x0e, 0x61, 0xd1, 0x1a, 0xec, 0x6f, 0x74, 0xed,
	0xec, 0x2d, 0x94, 0x0d, 0xde, 0xc7, 0x0e, 0x3e, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x95,
	0xf1, 0x12, 0x31, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Put(ctx context.Context, in *Port, opts ...grpc.CallOption) (*PutResponse, error)
}

type portServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortServiceClient(cc *grpc.ClientConn) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/proto.PortService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portServiceClient) Put(ctx context.Context, in *Port, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/proto.PortService/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortServiceServer is the server API for PortService service.
type PortServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Put(context.Context, *Port) (*PutResponse, error)
}

func RegisterPortServiceServer(s *grpc.Server, srv PortServiceServer) {
	s.RegisterService(&_PortService_serviceDesc, srv)
}

func _PortService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Port)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PortService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortServiceServer).Put(ctx, req.(*Port))
	}
	return interceptor(ctx, in, info, handler)
}

var _PortService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _PortService_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _PortService_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "one.proto",
}
