app:
    resource: "@AppBundle/Controller/"
    type:     annotation
_index:
    path: /
    defaults: {_controller: AppBundle:Index:Index}
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
github_login:
    path: /login/check-github
