modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - wsl
    - varnamelen
    - nilnil
    - gochecknoglobals
    - funlen
    - goerr113
    - gci
    - paralleltest
    - ireturn
    - forbidigo
    - gofumpt
    - exhaustivestruct
    - nolintlint
    - tagliatelle
    - wrapcheck
    - scopelint
    - gochecknoinits
    - goimports
    - maligned
    - godot
    - prealloc
    - gocritic
    - interfacer
    - golint
    - godox
    - exhaustruct
    - ifshort
    - varcheck
    - structcheck
    - deadcode
    - nosnakecase
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - typecheck
    - nlreturn
    - thelper
    - lll
    - contextcheck
    - nonamedreturns
    - unparam
    - gomnd
    - cyclop

linters-settings:
  gomnd:
    settings:
      mnd:
        checks: case,condition,return

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - testpackage
        - maligned
        - dupl
        - lll
        - cyclop
    - linters:
        - gosec
      text: "G401: "
    - linters:
        - gosec
      text: "G505: "
