Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.synced_folder "../../../../ed/elasticsearch/", "/var/www/elasticsearch"
  config.vm.provision :shell, path: "bootstrap.sh"
end
