version: 2

jobs:
  build:
    environment:
      ENV_VAR_NAME: ENV_VAR_VALUE

    docker:

      # - image: google/cloud-sdk:latest
      - image: circleci/golang:1.9
          auth:
            username: $DOCKER_USER
            password: $DOCKER_PASSWORD

      - image: gcr.io/cl-dev/cws-circleci
         auth:
            username: _json_key
            # password - don't contain password
            # but contain JSON contet of service_account_key file.
            password: $GOOGLE_CLOUD_SERVICE_ACCOUNT

    working_directory: /code
    working_directory: /go/src/github.com/cn007b/api-gateway

    steps:
      - checkout

      - run: echo "run some tests"

      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - run: go get -u golang.org/x/lint/golint
      - run: golint src/app/...


      # - run: go get -v -t -d ./...
      # - run: go vet
      # - run: go test -v ./...

      # - run: go test -v -covermode=count -coverprofile=coverage.out
      # - run: goveralls -coverprofile=coverage.out -service=circle-ci
