
mysql-master:
    image: mysql:latest
    container_name: mysql-master
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=dbu
        - MYSQL_PASSWORD=dbp
    ports:
        - "3307:3306"
    volumes:
        - ./docker/mysql/mysql-bin.log:/var/log/mysql/mysql-bin.log
        - ./config-master.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

mysql-slave-1:
    image: mysql:latest
    container_name: mysql-slave-1
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=dbu2
        - MYSQL_PASSWORD=dbp2
    ports:
        - "3308:3306"
    volumes:
        - ./docker/mysql/mysql-bin.log:/var/log/mysql/mysql-bin.log
        - ./config-slave-1.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    links:
        - mysql-master

# After all run next commands:
#
# ON MASTER:
#
# docker-compose exec mysql-master mysql -uroot -proot -e "CREATE USER 'repl'@'%' IDENTIFIED BY 'slavepass'"
# docker-compose exec mysql-master mysql -uroot -proot -e "GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%'"
#
# ON SLAVE 1:
#
# docker-compose exec mysql-slave-1 mysql -uroot -proot -e "CHANGE MASTER TO MASTER_HOST='mysql-master', MASTER_USER='repl', MASTER_PASSWORD='slavepass'"
# docker-compose exec mysql-slave-1 mysql -uroot -proot -e "START SLAVE"
# docker-compose exec mysql-slave-1 mysql -uroot -proot -e "SHOW SLAVE STATUS \G"
