web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./src:/var/www/html
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php-fpm
php-fpm:
    image: php:7.1-fpm
    volumes:
        - ./src:/var/www/html
