web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./src:/src
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    image: php:7.1-fpm
    volumes:
        - ./src:/src
