// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateToteAssignmentHandlerFunc turns a function with the right signature into a create tote assignment handler
type CreateToteAssignmentHandlerFunc func(CreateToteAssignmentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateToteAssignmentHandlerFunc) Handle(params CreateToteAssignmentParams) middleware.Responder {
	return fn(params)
}

// CreateToteAssignmentHandler interface for that can handle valid create tote assignment params
type CreateToteAssignmentHandler interface {
	Handle(CreateToteAssignmentParams) middleware.Responder
}

// NewCreateToteAssignment creates a new http.Handler for the create tote assignment operation
func NewCreateToteAssignment(ctx *middleware.Context, handler CreateToteAssignmentHandler) *CreateToteAssignment {
	return &CreateToteAssignment{Context: ctx, Handler: handler}
}

/* CreateToteAssignment swagger:route POST /clients/{clientId}/mfcs/{mfcId}/toteAssignments/{toteAssignmentId} createToteAssignment

Create tote assignment wit order and lane.

*/
type CreateToteAssignment struct {
	Context *middleware.Context
	Handler CreateToteAssignmentHandler
}

func (o *CreateToteAssignment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateToteAssignmentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
