// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// DeleteToteAssignmentURL generates an URL for the delete tote assignment operation
type DeleteToteAssignmentURL struct {
	ClientID string
	MfcID    string

	ToteID []string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteToteAssignmentURL) WithBasePath(bp string) *DeleteToteAssignmentURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteToteAssignmentURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteToteAssignmentURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/clients/{clientId}/mfcs/{mfcId}/toteAssignments"

	clientID := o.ClientID
	if clientID != "" {
		_path = strings.Replace(_path, "{clientId}", clientID, -1)
	} else {
		return nil, errors.New("clientId is required on DeleteToteAssignmentURL")
	}

	mfcID := o.MfcID
	if mfcID != "" {
		_path = strings.Replace(_path, "{mfcId}", mfcID, -1)
	} else {
		return nil, errors.New("mfcId is required on DeleteToteAssignmentURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v2"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var toteIDIR []string
	for _, toteIDI := range o.ToteID {
		toteIDIS := toteIDI
		if toteIDIS != "" {
			toteIDIR = append(toteIDIR, toteIDIS)
		}
	}

	toteID := swag.JoinByFormat(toteIDIR, "multi")

	for _, qsv := range toteID {
		qs.Add("toteId", qsv)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteToteAssignmentURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteToteAssignmentURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteToteAssignmentURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteToteAssignmentURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteToteAssignmentURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteToteAssignmentURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
