// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetConfigsParams creates a new GetConfigsParams object
//
// There are no default values defined in the spec.
func NewGetConfigsParams() GetConfigsParams {

	return GetConfigsParams{}
}

// GetConfigsParams contains all the bound params for the get configs operation
// typically these are obtained from a http.Request
//
// swagger:parameters getConfigs
type GetConfigsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	ClientID string
	/*
	  Required: true
	  In: path
	*/
	MfcID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetConfigsParams() beforehand.
func (o *GetConfigsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rClientID, rhkClientID, _ := route.Params.GetOK("clientId")
	if err := o.bindClientID(rClientID, rhkClientID, route.Formats); err != nil {
		res = append(res, err)
	}

	rMfcID, rhkMfcID, _ := route.Params.GetOK("mfcId")
	if err := o.bindMfcID(rMfcID, rhkMfcID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindClientID binds and validates parameter ClientID from path.
func (o *GetConfigsParams) bindClientID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ClientID = raw

	return nil
}

// bindMfcID binds and validates parameter MfcID from path.
func (o *GetConfigsParams) bindMfcID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.MfcID = raw

	return nil
}
