// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/to-com/poc-td/app/swagger/restmodel"
)

// HealthCheckOKCode is the HTTP code returned for type HealthCheckOK
const HealthCheckOKCode int = 200

/*HealthCheckOK Successful response.

swagger:response healthCheckOK
*/
type HealthCheckOK struct {
}

// NewHealthCheckOK creates HealthCheckOK with default headers values
func NewHealthCheckOK() *HealthCheckOK {

	return &HealthCheckOK{}
}

// WriteResponse to the client
func (o *HealthCheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// HealthCheckBadRequestCode is the HTTP code returned for type HealthCheckBadRequest
const HealthCheckBadRequestCode int = 400

/*HealthCheckBadRequest Bad Request.

swagger:response healthCheckBadRequest
*/
type HealthCheckBadRequest struct {

	/*
	  In: Body
	*/
	Payload *restmodel.Response400 `json:"body,omitempty"`
}

// NewHealthCheckBadRequest creates HealthCheckBadRequest with default headers values
func NewHealthCheckBadRequest() *HealthCheckBadRequest {

	return &HealthCheckBadRequest{}
}

// WithPayload adds the payload to the health check bad request response
func (o *HealthCheckBadRequest) WithPayload(payload *restmodel.Response400) *HealthCheckBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the health check bad request response
func (o *HealthCheckBadRequest) SetPayload(payload *restmodel.Response400) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *HealthCheckBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
