// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPocToteDispatcherAPI creates a new PocToteDispatcher instance
func NewPocToteDispatcherAPI(spec *loads.Document) *PocToteDispatcherAPI {
	return &PocToteDispatcherAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		CreateToteAssignmentHandler: CreateToteAssignmentHandlerFunc(func(params CreateToteAssignmentParams) middleware.Responder {
			return middleware.NotImplemented("operation CreateToteAssignment has not yet been implemented")
		}),
		DeleteToteAssignmentHandler: DeleteToteAssignmentHandlerFunc(func(params DeleteToteAssignmentParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteToteAssignment has not yet been implemented")
		}),
		GetConfigsHandler: GetConfigsHandlerFunc(func(params GetConfigsParams) middleware.Responder {
			return middleware.NotImplemented("operation GetConfigs has not yet been implemented")
		}),
		HealthCheckHandler: HealthCheckHandlerFunc(func(params HealthCheckParams) middleware.Responder {
			return middleware.NotImplemented("operation HealthCheck has not yet been implemented")
		}),
		ListToteAssignmentsHandler: ListToteAssignmentsHandlerFunc(func(params ListToteAssignmentsParams) middleware.Responder {
			return middleware.NotImplemented("operation ListToteAssignments has not yet been implemented")
		}),
		UpdateConfigHandler: UpdateConfigHandlerFunc(func(params UpdateConfigParams) middleware.Responder {
			return middleware.NotImplemented("operation UpdateConfig has not yet been implemented")
		}),
		UpdateToteAssignmentHandler: UpdateToteAssignmentHandlerFunc(func(params UpdateToteAssignmentParams) middleware.Responder {
			return middleware.NotImplemented("operation UpdateToteAssignment has not yet been implemented")
		}),
	}
}

/*PocToteDispatcherAPI API for dispatch lane and flow rack. */
type PocToteDispatcherAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// CreateToteAssignmentHandler sets the operation handler for the create tote assignment operation
	CreateToteAssignmentHandler CreateToteAssignmentHandler
	// DeleteToteAssignmentHandler sets the operation handler for the delete tote assignment operation
	DeleteToteAssignmentHandler DeleteToteAssignmentHandler
	// GetConfigsHandler sets the operation handler for the get configs operation
	GetConfigsHandler GetConfigsHandler
	// HealthCheckHandler sets the operation handler for the health check operation
	HealthCheckHandler HealthCheckHandler
	// ListToteAssignmentsHandler sets the operation handler for the list tote assignments operation
	ListToteAssignmentsHandler ListToteAssignmentsHandler
	// UpdateConfigHandler sets the operation handler for the update config operation
	UpdateConfigHandler UpdateConfigHandler
	// UpdateToteAssignmentHandler sets the operation handler for the update tote assignment operation
	UpdateToteAssignmentHandler UpdateToteAssignmentHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *PocToteDispatcherAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *PocToteDispatcherAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *PocToteDispatcherAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *PocToteDispatcherAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *PocToteDispatcherAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *PocToteDispatcherAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *PocToteDispatcherAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *PocToteDispatcherAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *PocToteDispatcherAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the PocToteDispatcherAPI
func (o *PocToteDispatcherAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.CreateToteAssignmentHandler == nil {
		unregistered = append(unregistered, "CreateToteAssignmentHandler")
	}
	if o.DeleteToteAssignmentHandler == nil {
		unregistered = append(unregistered, "DeleteToteAssignmentHandler")
	}
	if o.GetConfigsHandler == nil {
		unregistered = append(unregistered, "GetConfigsHandler")
	}
	if o.HealthCheckHandler == nil {
		unregistered = append(unregistered, "HealthCheckHandler")
	}
	if o.ListToteAssignmentsHandler == nil {
		unregistered = append(unregistered, "ListToteAssignmentsHandler")
	}
	if o.UpdateConfigHandler == nil {
		unregistered = append(unregistered, "UpdateConfigHandler")
	}
	if o.UpdateToteAssignmentHandler == nil {
		unregistered = append(unregistered, "UpdateToteAssignmentHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *PocToteDispatcherAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *PocToteDispatcherAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *PocToteDispatcherAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *PocToteDispatcherAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *PocToteDispatcherAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *PocToteDispatcherAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the poc tote dispatcher API
func (o *PocToteDispatcherAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *PocToteDispatcherAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/clients/{clientId}/mfcs/{mfcId}/toteAssignments/{toteAssignmentId}"] = NewCreateToteAssignment(o.context, o.CreateToteAssignmentHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/clients/{clientId}/mfcs/{mfcId}/toteAssignments"] = NewDeleteToteAssignment(o.context, o.DeleteToteAssignmentHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/clients/{clientId}/mfcs/{mfcId}/configs"] = NewGetConfigs(o.context, o.GetConfigsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/health"] = NewHealthCheck(o.context, o.HealthCheckHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/clients/{clientId}/mfcs/{mfcId}/toteAssignments"] = NewListToteAssignments(o.context, o.ListToteAssignmentsHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/clients/{clientId}/mfcs/{mfcId}/configs"] = NewUpdateConfig(o.context, o.UpdateConfigHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/clients/{clientId}/mfcs/{mfcId}/toteAssignments/{toteAssignmentId}"] = NewUpdateToteAssignment(o.context, o.UpdateToteAssignmentHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *PocToteDispatcherAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *PocToteDispatcherAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *PocToteDispatcherAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *PocToteDispatcherAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *PocToteDispatcherAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
