// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateConfigHandlerFunc turns a function with the right signature into a update config handler
type UpdateConfigHandlerFunc func(UpdateConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateConfigHandlerFunc) Handle(params UpdateConfigParams) middleware.Responder {
	return fn(params)
}

// UpdateConfigHandler interface for that can handle valid update config params
type UpdateConfigHandler interface {
	Handle(UpdateConfigParams) middleware.Responder
}

// NewUpdateConfig creates a new http.Handler for the update config operation
func NewUpdateConfig(ctx *middleware.Context, handler UpdateConfigHandler) *UpdateConfig {
	return &UpdateConfig{Context: ctx, Handler: handler}
}

/* UpdateConfig swagger:route PUT /clients/{clientId}/mfcs/{mfcId}/configs updateConfig

Update config.

*/
type UpdateConfig struct {
	Context *middleware.Context
	Handler UpdateConfigHandler
}

func (o *UpdateConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateConfigParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
