// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/to-com/poc-td/app/swagger/restmodel"
)

// UpdateToteAssignmentOKCode is the HTTP code returned for type UpdateToteAssignmentOK
const UpdateToteAssignmentOKCode int = 200

/*UpdateToteAssignmentOK Successful response.

swagger:response updateToteAssignmentOK
*/
type UpdateToteAssignmentOK struct {

	/*
	  In: Body
	*/
	Payload *restmodel.UpdateToteAssignmentResponse `json:"body,omitempty"`
}

// NewUpdateToteAssignmentOK creates UpdateToteAssignmentOK with default headers values
func NewUpdateToteAssignmentOK() *UpdateToteAssignmentOK {

	return &UpdateToteAssignmentOK{}
}

// WithPayload adds the payload to the update tote assignment o k response
func (o *UpdateToteAssignmentOK) WithPayload(payload *restmodel.UpdateToteAssignmentResponse) *UpdateToteAssignmentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update tote assignment o k response
func (o *UpdateToteAssignmentOK) SetPayload(payload *restmodel.UpdateToteAssignmentResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateToteAssignmentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateToteAssignmentBadRequestCode is the HTTP code returned for type UpdateToteAssignmentBadRequest
const UpdateToteAssignmentBadRequestCode int = 400

/*UpdateToteAssignmentBadRequest Bad Request.

swagger:response updateToteAssignmentBadRequest
*/
type UpdateToteAssignmentBadRequest struct {

	/*
	  In: Body
	*/
	Payload *restmodel.Response400 `json:"body,omitempty"`
}

// NewUpdateToteAssignmentBadRequest creates UpdateToteAssignmentBadRequest with default headers values
func NewUpdateToteAssignmentBadRequest() *UpdateToteAssignmentBadRequest {

	return &UpdateToteAssignmentBadRequest{}
}

// WithPayload adds the payload to the update tote assignment bad request response
func (o *UpdateToteAssignmentBadRequest) WithPayload(payload *restmodel.Response400) *UpdateToteAssignmentBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update tote assignment bad request response
func (o *UpdateToteAssignmentBadRequest) SetPayload(payload *restmodel.Response400) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateToteAssignmentBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
