// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// UpdateToteAssignmentURL generates an URL for the update tote assignment operation
type UpdateToteAssignmentURL struct {
	ClientID         string
	MfcID            string
	ToteAssignmentID string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdateToteAssignmentURL) WithBasePath(bp string) *UpdateToteAssignmentURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *UpdateToteAssignmentURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *UpdateToteAssignmentURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/clients/{clientId}/mfcs/{mfcId}/toteAssignments/{toteAssignmentId}"

	clientID := o.ClientID
	if clientID != "" {
		_path = strings.Replace(_path, "{clientId}", clientID, -1)
	} else {
		return nil, errors.New("clientId is required on UpdateToteAssignmentURL")
	}

	mfcID := o.MfcID
	if mfcID != "" {
		_path = strings.Replace(_path, "{mfcId}", mfcID, -1)
	} else {
		return nil, errors.New("mfcId is required on UpdateToteAssignmentURL")
	}

	toteAssignmentID := o.ToteAssignmentID
	if toteAssignmentID != "" {
		_path = strings.Replace(_path, "{toteAssignmentId}", toteAssignmentID, -1)
	} else {
		return nil, errors.New("toteAssignmentId is required on UpdateToteAssignmentURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v2"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *UpdateToteAssignmentURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *UpdateToteAssignmentURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *UpdateToteAssignmentURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on UpdateToteAssignmentURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on UpdateToteAssignmentURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *UpdateToteAssignmentURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
