Vagrant.configure(2) do |config|
  config.vm.box = "puphpet/centos65-x64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "../../../../helper", "/var/www/helper"
  config.vm.provision :shell, path: "bootstrap.sh"

  if Vagrant.has_plugin?("vagrant-cachier")
  end
end
