parameters:

services:
    log_reader:
        class: AppBundle\DependencyInjection\LogReader
        arguments:
            - @doctrine.orm.entity_manager
            - @log_saver
            - 'default'
            - '/home/bond/web/kovpak/gh/ed/symfony/examples/LogViewer/app/logs/'
    log_saver:
        class: AppBundle\DependencyInjection\LogSaver
        arguments:
            - @doctrine.orm.entity_manager
