name: Cloud Run

on:
  push:
    branches:
      - master
    paths:
      - "**"
  pull_request:
    paths:
      - "**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Cloud run env"
        required: true
        default: "sandbox"

env:
  working-directory: "${{ github.workspace }}"

defaults:
  run:
    working-directory: .

jobs:
  load-config:
    name: Load Config
    runs-on: ubuntu-latest
    outputs:
      sandbox-config: ${{ steps.load-config-sandbox.outputs.config }}
    steps:
      - uses: actions/checkout@v2
      - id: load-config-sandbox
        run: echo "::set-output name=config::$(jq .sandbox ${{ env.workflow-directory }}/config.json -c)"

  create-build:
    name: Create and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to gcr.io Docker Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_SANDBOX }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          build-args: DOCKER_BUILD_IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/golang:latest
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/svc:latest

  deploy-sandbox:
    name: Deploy sandbox

    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'sandbox') ||
        (github.event_name == 'push' && github.ref == 'refs/heads/master') ||
        contains(github.event.pull_request.labels.*.name, 'auto-deploy-sandbox')

    runs-on: ubuntu-latest
    needs:
      - load-config
    strategy:
      matrix:
        region: ${{ fromJSON(needs.load-config.outputs.sandbox-config).regions }}
    steps:
      - uses: actions/checkout@v2

      - name: Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_SANDBOX }}

      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service: svc
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/svc:latest
          region: ${{ matrix.region }}
          env_vars: >
            ENV=sandbox,
            HOST=0.0.0.0,
            SPANNER_DATABASE=projects/${{ secrets.GCP_PROJECT_ID }}/instances/svc/databases/svc,
            GOOGLE_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}
          no_traffic: true

      - name: Route traffic to deployed revision
        run: >
          gcloud run services update-traffic svc
          --region ${{ matrix.region }}
          --project ${{ secrets.GCP_PROJECT_ID }}
          --to-latest
